// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD30Tyeqz3jedVLHVU4nRxCkNIHNZjGzPQ',
    appId: '1:658955667527:web:5838d9e0ce708454a70962',
    messagingSenderId: '658955667527',
    projectId: 'todo-for-trial',
    authDomain: 'todo-for-trial.firebaseapp.com',
    storageBucket: 'todo-for-trial.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi19ACi7bPa1rVaNA0HpqTukZ1TDKVGOs',
    appId: '1:658955667527:android:2b0be9e087f09b3da70962',
    messagingSenderId: '658955667527',
    projectId: 'todo-for-trial',
    storageBucket: 'todo-for-trial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4_R76zyC5Q4ymGcxd3fbWhXBge2pw928',
    appId: '1:658955667527:ios:2e31ca5b9e8ba688a70962',
    messagingSenderId: '658955667527',
    projectId: 'todo-for-trial',
    storageBucket: 'todo-for-trial.appspot.com',
    iosClientId: '658955667527-f6ancdr1l74fki59l09vs2f9etcfo55d.apps.googleusercontent.com',
    iosBundleId: 'com.example.traialtodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4_R76zyC5Q4ymGcxd3fbWhXBge2pw928',
    appId: '1:658955667527:ios:2e31ca5b9e8ba688a70962',
    messagingSenderId: '658955667527',
    projectId: 'todo-for-trial',
    storageBucket: 'todo-for-trial.appspot.com',
    iosClientId: '658955667527-f6ancdr1l74fki59l09vs2f9etcfo55d.apps.googleusercontent.com',
    iosBundleId: 'com.example.traialtodo',
  );
}
